version: '3.7'
services:
  postgres:
    image: repository.dimas-maryanto.com:8086/postgres:12.1
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=example
      - POSTGRES_DB=example
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network
volumes:
  postgres_data:
networks:
  postgres-network:
